name: ML Model Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision
        
    - name: Check model file exists
      run: |
        if [ ! -f "model.pth" ]; then
          echo "Error: model.pth file not found"
          exit 1
        fi
        
    - name: Run tests
      run: |
        python tests/test_model.py 